/*
ArborXR Public API

This API provides a RESTful interface to interact with your organization's data.

API version: v2
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the InviteUserRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteUserRequest{}

// InviteUserRequest struct for InviteUserRequest
type InviteUserRequest struct {
	Email string `json:"email"`
	// Should the user be required to authenticate using the organization's configured IdP?
	Sso *bool `json:"sso,omitempty"`
	// Required when `groupRoleId` & `groupIds` are not provided.
	OrganizationRoleId *string `json:"organizationRoleId,omitempty"`
	// Required when `organizationRoleId` is not provided.
	GroupRoleId *string `json:"groupRoleId,omitempty"`
	// Required when `organizationRoleId` is not provided.
	GroupIds []string `json:"groupIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InviteUserRequest InviteUserRequest

// NewInviteUserRequest instantiates a new InviteUserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteUserRequest(email string) *InviteUserRequest {
	this := InviteUserRequest{}
	this.Email = email
	return &this
}

// NewInviteUserRequestWithDefaults instantiates a new InviteUserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteUserRequestWithDefaults() *InviteUserRequest {
	this := InviteUserRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *InviteUserRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *InviteUserRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *InviteUserRequest) SetEmail(v string) {
	o.Email = v
}

// GetSso returns the Sso field value if set, zero value otherwise.
func (o *InviteUserRequest) GetSso() bool {
	if o == nil || IsNil(o.Sso) {
		var ret bool
		return ret
	}
	return *o.Sso
}

// GetSsoOk returns a tuple with the Sso field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteUserRequest) GetSsoOk() (*bool, bool) {
	if o == nil || IsNil(o.Sso) {
		return nil, false
	}
	return o.Sso, true
}

// HasSso returns a boolean if a field has been set.
func (o *InviteUserRequest) HasSso() bool {
	if o != nil && !IsNil(o.Sso) {
		return true
	}

	return false
}

// SetSso gets a reference to the given bool and assigns it to the Sso field.
func (o *InviteUserRequest) SetSso(v bool) {
	o.Sso = &v
}

// GetOrganizationRoleId returns the OrganizationRoleId field value if set, zero value otherwise.
func (o *InviteUserRequest) GetOrganizationRoleId() string {
	if o == nil || IsNil(o.OrganizationRoleId) {
		var ret string
		return ret
	}
	return *o.OrganizationRoleId
}

// GetOrganizationRoleIdOk returns a tuple with the OrganizationRoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteUserRequest) GetOrganizationRoleIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationRoleId) {
		return nil, false
	}
	return o.OrganizationRoleId, true
}

// HasOrganizationRoleId returns a boolean if a field has been set.
func (o *InviteUserRequest) HasOrganizationRoleId() bool {
	if o != nil && !IsNil(o.OrganizationRoleId) {
		return true
	}

	return false
}

// SetOrganizationRoleId gets a reference to the given string and assigns it to the OrganizationRoleId field.
func (o *InviteUserRequest) SetOrganizationRoleId(v string) {
	o.OrganizationRoleId = &v
}

// GetGroupRoleId returns the GroupRoleId field value if set, zero value otherwise.
func (o *InviteUserRequest) GetGroupRoleId() string {
	if o == nil || IsNil(o.GroupRoleId) {
		var ret string
		return ret
	}
	return *o.GroupRoleId
}

// GetGroupRoleIdOk returns a tuple with the GroupRoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteUserRequest) GetGroupRoleIdOk() (*string, bool) {
	if o == nil || IsNil(o.GroupRoleId) {
		return nil, false
	}
	return o.GroupRoleId, true
}

// HasGroupRoleId returns a boolean if a field has been set.
func (o *InviteUserRequest) HasGroupRoleId() bool {
	if o != nil && !IsNil(o.GroupRoleId) {
		return true
	}

	return false
}

// SetGroupRoleId gets a reference to the given string and assigns it to the GroupRoleId field.
func (o *InviteUserRequest) SetGroupRoleId(v string) {
	o.GroupRoleId = &v
}

// GetGroupIds returns the GroupIds field value if set, zero value otherwise.
func (o *InviteUserRequest) GetGroupIds() []string {
	if o == nil || IsNil(o.GroupIds) {
		var ret []string
		return ret
	}
	return o.GroupIds
}

// GetGroupIdsOk returns a tuple with the GroupIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteUserRequest) GetGroupIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupIds) {
		return nil, false
	}
	return o.GroupIds, true
}

// HasGroupIds returns a boolean if a field has been set.
func (o *InviteUserRequest) HasGroupIds() bool {
	if o != nil && !IsNil(o.GroupIds) {
		return true
	}

	return false
}

// SetGroupIds gets a reference to the given []string and assigns it to the GroupIds field.
func (o *InviteUserRequest) SetGroupIds(v []string) {
	o.GroupIds = v
}

func (o InviteUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteUserRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.Sso) {
		toSerialize["sso"] = o.Sso
	}
	if !IsNil(o.OrganizationRoleId) {
		toSerialize["organizationRoleId"] = o.OrganizationRoleId
	}
	if !IsNil(o.GroupRoleId) {
		toSerialize["groupRoleId"] = o.GroupRoleId
	}
	if !IsNil(o.GroupIds) {
		toSerialize["groupIds"] = o.GroupIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InviteUserRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteUserRequest := _InviteUserRequest{}

	err = json.Unmarshal(data, &varInviteUserRequest)

	if err != nil {
		return err
	}

	*o = InviteUserRequest(varInviteUserRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "email")
		delete(additionalProperties, "sso")
		delete(additionalProperties, "organizationRoleId")
		delete(additionalProperties, "groupRoleId")
		delete(additionalProperties, "groupIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInviteUserRequest struct {
	value *InviteUserRequest
	isSet bool
}

func (v NullableInviteUserRequest) Get() *InviteUserRequest {
	return v.value
}

func (v *NullableInviteUserRequest) Set(val *InviteUserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteUserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteUserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteUserRequest(val *InviteUserRequest) *NullableInviteUserRequest {
	return &NullableInviteUserRequest{value: val, isSet: true}
}

func (v NullableInviteUserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteUserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


