/*
ArborXR Public API

This API provides a RESTful interface to interact with your organization's data.

API version: v2
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetDevices200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDevices200ResponseDataInner{}

// GetDevices200ResponseDataInner struct for GetDevices200ResponseDataInner
type GetDevices200ResponseDataInner struct {
	Id *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	SerialNumber *string `json:"serialNumber,omitempty"`
	DeviceGroup NullableString `json:"deviceGroup,omitempty"`
	Group *GetDeviceGroups200ResponseDataInner `json:"group,omitempty"`
	Model *string `json:"model,omitempty"`
	Tags []string `json:"tags,omitempty"`
	LastCommunicatedAt NullableString `json:"lastCommunicatedAt,omitempty"`
	IsOnline NullableBool `json:"isOnline,omitempty"`
	ClientVersion NullableString `json:"clientVersion,omitempty"`
	LauncherVersion NullableString `json:"launcherVersion,omitempty"`
	EnrollmentDate NullableString `json:"enrollmentDate,omitempty"`
	SystemVersion NullableString `json:"systemVersion,omitempty"`
	OsVersion NullableString `json:"osVersion,omitempty"`
	Ssid NullableString `json:"ssid,omitempty"`
	MacAddress NullableString `json:"macAddress,omitempty"`
	RandomizedMacAddress NullableString `json:"randomizedMacAddress,omitempty"`
	StorageSpaceFreeGb NullableFloat32 `json:"storageSpaceFreeGb,omitempty"`
	StorageSpaceTotalGb NullableFloat32 `json:"storageSpaceTotalGb,omitempty"`
	BatteryHealth NullableString `json:"batteryHealth,omitempty"`
	BatteryCharging NullableBool `json:"batteryCharging,omitempty"`
	BatteryPercentage NullableInt32 `json:"batteryPercentage,omitempty"`
	BatteryTemperatureC NullableFloat32 `json:"batteryTemperatureC,omitempty"`
	IpAddress NullableString `json:"ipAddress,omitempty"`
	SignalStrength NullableFloat32 `json:"signalStrength,omitempty"`
	FrequencyMhz NullableInt32 `json:"frequencyMhz,omitempty"`
	LinkSpeedMbps NullableInt32 `json:"linkSpeedMbps,omitempty"`
	LastLocationLatitude NullableFloat32 `json:"lastLocationLatitude,omitempty"`
	LastLocationLongitude NullableFloat32 `json:"lastLocationLongitude,omitempty"`
	LastLocationAt NullableString `json:"lastLocationAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetDevices200ResponseDataInner GetDevices200ResponseDataInner

// NewGetDevices200ResponseDataInner instantiates a new GetDevices200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDevices200ResponseDataInner() *GetDevices200ResponseDataInner {
	this := GetDevices200ResponseDataInner{}
	return &this
}

// NewGetDevices200ResponseDataInnerWithDefaults instantiates a new GetDevices200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDevices200ResponseDataInnerWithDefaults() *GetDevices200ResponseDataInner {
	this := GetDevices200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetDevices200ResponseDataInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDevices200ResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetDevices200ResponseDataInner) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetDevices200ResponseDataInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDevices200ResponseDataInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetDevices200ResponseDataInner) SetTitle(v string) {
	o.Title = &v
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise.
func (o *GetDevices200ResponseDataInner) GetSerialNumber() string {
	if o == nil || IsNil(o.SerialNumber) {
		var ret string
		return ret
	}
	return *o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDevices200ResponseDataInner) GetSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SerialNumber) {
		return nil, false
	}
	return o.SerialNumber, true
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasSerialNumber() bool {
	if o != nil && !IsNil(o.SerialNumber) {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given string and assigns it to the SerialNumber field.
func (o *GetDevices200ResponseDataInner) SetSerialNumber(v string) {
	o.SerialNumber = &v
}

// GetDeviceGroup returns the DeviceGroup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetDeviceGroup() string {
	if o == nil || IsNil(o.DeviceGroup.Get()) {
		var ret string
		return ret
	}
	return *o.DeviceGroup.Get()
}

// GetDeviceGroupOk returns a tuple with the DeviceGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetDeviceGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceGroup.Get(), o.DeviceGroup.IsSet()
}

// HasDeviceGroup returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasDeviceGroup() bool {
	if o != nil && o.DeviceGroup.IsSet() {
		return true
	}

	return false
}

// SetDeviceGroup gets a reference to the given NullableString and assigns it to the DeviceGroup field.
func (o *GetDevices200ResponseDataInner) SetDeviceGroup(v string) {
	o.DeviceGroup.Set(&v)
}
// SetDeviceGroupNil sets the value for DeviceGroup to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetDeviceGroupNil() {
	o.DeviceGroup.Set(nil)
}

// UnsetDeviceGroup ensures that no value is present for DeviceGroup, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetDeviceGroup() {
	o.DeviceGroup.Unset()
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *GetDevices200ResponseDataInner) GetGroup() GetDeviceGroups200ResponseDataInner {
	if o == nil || IsNil(o.Group) {
		var ret GetDeviceGroups200ResponseDataInner
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDevices200ResponseDataInner) GetGroupOk() (*GetDeviceGroups200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given GetDeviceGroups200ResponseDataInner and assigns it to the Group field.
func (o *GetDevices200ResponseDataInner) SetGroup(v GetDeviceGroups200ResponseDataInner) {
	o.Group = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *GetDevices200ResponseDataInner) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDevices200ResponseDataInner) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *GetDevices200ResponseDataInner) SetModel(v string) {
	o.Model = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *GetDevices200ResponseDataInner) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDevices200ResponseDataInner) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *GetDevices200ResponseDataInner) SetTags(v []string) {
	o.Tags = v
}

// GetLastCommunicatedAt returns the LastCommunicatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetLastCommunicatedAt() string {
	if o == nil || IsNil(o.LastCommunicatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.LastCommunicatedAt.Get()
}

// GetLastCommunicatedAtOk returns a tuple with the LastCommunicatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetLastCommunicatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastCommunicatedAt.Get(), o.LastCommunicatedAt.IsSet()
}

// HasLastCommunicatedAt returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasLastCommunicatedAt() bool {
	if o != nil && o.LastCommunicatedAt.IsSet() {
		return true
	}

	return false
}

// SetLastCommunicatedAt gets a reference to the given NullableString and assigns it to the LastCommunicatedAt field.
func (o *GetDevices200ResponseDataInner) SetLastCommunicatedAt(v string) {
	o.LastCommunicatedAt.Set(&v)
}
// SetLastCommunicatedAtNil sets the value for LastCommunicatedAt to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetLastCommunicatedAtNil() {
	o.LastCommunicatedAt.Set(nil)
}

// UnsetLastCommunicatedAt ensures that no value is present for LastCommunicatedAt, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetLastCommunicatedAt() {
	o.LastCommunicatedAt.Unset()
}

// GetIsOnline returns the IsOnline field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetIsOnline() bool {
	if o == nil || IsNil(o.IsOnline.Get()) {
		var ret bool
		return ret
	}
	return *o.IsOnline.Get()
}

// GetIsOnlineOk returns a tuple with the IsOnline field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetIsOnlineOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsOnline.Get(), o.IsOnline.IsSet()
}

// HasIsOnline returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasIsOnline() bool {
	if o != nil && o.IsOnline.IsSet() {
		return true
	}

	return false
}

// SetIsOnline gets a reference to the given NullableBool and assigns it to the IsOnline field.
func (o *GetDevices200ResponseDataInner) SetIsOnline(v bool) {
	o.IsOnline.Set(&v)
}
// SetIsOnlineNil sets the value for IsOnline to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetIsOnlineNil() {
	o.IsOnline.Set(nil)
}

// UnsetIsOnline ensures that no value is present for IsOnline, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetIsOnline() {
	o.IsOnline.Unset()
}

// GetClientVersion returns the ClientVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetClientVersion() string {
	if o == nil || IsNil(o.ClientVersion.Get()) {
		var ret string
		return ret
	}
	return *o.ClientVersion.Get()
}

// GetClientVersionOk returns a tuple with the ClientVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetClientVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClientVersion.Get(), o.ClientVersion.IsSet()
}

// HasClientVersion returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasClientVersion() bool {
	if o != nil && o.ClientVersion.IsSet() {
		return true
	}

	return false
}

// SetClientVersion gets a reference to the given NullableString and assigns it to the ClientVersion field.
func (o *GetDevices200ResponseDataInner) SetClientVersion(v string) {
	o.ClientVersion.Set(&v)
}
// SetClientVersionNil sets the value for ClientVersion to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetClientVersionNil() {
	o.ClientVersion.Set(nil)
}

// UnsetClientVersion ensures that no value is present for ClientVersion, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetClientVersion() {
	o.ClientVersion.Unset()
}

// GetLauncherVersion returns the LauncherVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetLauncherVersion() string {
	if o == nil || IsNil(o.LauncherVersion.Get()) {
		var ret string
		return ret
	}
	return *o.LauncherVersion.Get()
}

// GetLauncherVersionOk returns a tuple with the LauncherVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetLauncherVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LauncherVersion.Get(), o.LauncherVersion.IsSet()
}

// HasLauncherVersion returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasLauncherVersion() bool {
	if o != nil && o.LauncherVersion.IsSet() {
		return true
	}

	return false
}

// SetLauncherVersion gets a reference to the given NullableString and assigns it to the LauncherVersion field.
func (o *GetDevices200ResponseDataInner) SetLauncherVersion(v string) {
	o.LauncherVersion.Set(&v)
}
// SetLauncherVersionNil sets the value for LauncherVersion to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetLauncherVersionNil() {
	o.LauncherVersion.Set(nil)
}

// UnsetLauncherVersion ensures that no value is present for LauncherVersion, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetLauncherVersion() {
	o.LauncherVersion.Unset()
}

// GetEnrollmentDate returns the EnrollmentDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetEnrollmentDate() string {
	if o == nil || IsNil(o.EnrollmentDate.Get()) {
		var ret string
		return ret
	}
	return *o.EnrollmentDate.Get()
}

// GetEnrollmentDateOk returns a tuple with the EnrollmentDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetEnrollmentDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnrollmentDate.Get(), o.EnrollmentDate.IsSet()
}

// HasEnrollmentDate returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasEnrollmentDate() bool {
	if o != nil && o.EnrollmentDate.IsSet() {
		return true
	}

	return false
}

// SetEnrollmentDate gets a reference to the given NullableString and assigns it to the EnrollmentDate field.
func (o *GetDevices200ResponseDataInner) SetEnrollmentDate(v string) {
	o.EnrollmentDate.Set(&v)
}
// SetEnrollmentDateNil sets the value for EnrollmentDate to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetEnrollmentDateNil() {
	o.EnrollmentDate.Set(nil)
}

// UnsetEnrollmentDate ensures that no value is present for EnrollmentDate, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetEnrollmentDate() {
	o.EnrollmentDate.Unset()
}

// GetSystemVersion returns the SystemVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetSystemVersion() string {
	if o == nil || IsNil(o.SystemVersion.Get()) {
		var ret string
		return ret
	}
	return *o.SystemVersion.Get()
}

// GetSystemVersionOk returns a tuple with the SystemVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetSystemVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SystemVersion.Get(), o.SystemVersion.IsSet()
}

// HasSystemVersion returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasSystemVersion() bool {
	if o != nil && o.SystemVersion.IsSet() {
		return true
	}

	return false
}

// SetSystemVersion gets a reference to the given NullableString and assigns it to the SystemVersion field.
func (o *GetDevices200ResponseDataInner) SetSystemVersion(v string) {
	o.SystemVersion.Set(&v)
}
// SetSystemVersionNil sets the value for SystemVersion to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetSystemVersionNil() {
	o.SystemVersion.Set(nil)
}

// UnsetSystemVersion ensures that no value is present for SystemVersion, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetSystemVersion() {
	o.SystemVersion.Unset()
}

// GetOsVersion returns the OsVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetOsVersion() string {
	if o == nil || IsNil(o.OsVersion.Get()) {
		var ret string
		return ret
	}
	return *o.OsVersion.Get()
}

// GetOsVersionOk returns a tuple with the OsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetOsVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OsVersion.Get(), o.OsVersion.IsSet()
}

// HasOsVersion returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasOsVersion() bool {
	if o != nil && o.OsVersion.IsSet() {
		return true
	}

	return false
}

// SetOsVersion gets a reference to the given NullableString and assigns it to the OsVersion field.
func (o *GetDevices200ResponseDataInner) SetOsVersion(v string) {
	o.OsVersion.Set(&v)
}
// SetOsVersionNil sets the value for OsVersion to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetOsVersionNil() {
	o.OsVersion.Set(nil)
}

// UnsetOsVersion ensures that no value is present for OsVersion, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetOsVersion() {
	o.OsVersion.Unset()
}

// GetSsid returns the Ssid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetSsid() string {
	if o == nil || IsNil(o.Ssid.Get()) {
		var ret string
		return ret
	}
	return *o.Ssid.Get()
}

// GetSsidOk returns a tuple with the Ssid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetSsidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ssid.Get(), o.Ssid.IsSet()
}

// HasSsid returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasSsid() bool {
	if o != nil && o.Ssid.IsSet() {
		return true
	}

	return false
}

// SetSsid gets a reference to the given NullableString and assigns it to the Ssid field.
func (o *GetDevices200ResponseDataInner) SetSsid(v string) {
	o.Ssid.Set(&v)
}
// SetSsidNil sets the value for Ssid to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetSsidNil() {
	o.Ssid.Set(nil)
}

// UnsetSsid ensures that no value is present for Ssid, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetSsid() {
	o.Ssid.Unset()
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress.Get()) {
		var ret string
		return ret
	}
	return *o.MacAddress.Get()
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MacAddress.Get(), o.MacAddress.IsSet()
}

// HasMacAddress returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasMacAddress() bool {
	if o != nil && o.MacAddress.IsSet() {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given NullableString and assigns it to the MacAddress field.
func (o *GetDevices200ResponseDataInner) SetMacAddress(v string) {
	o.MacAddress.Set(&v)
}
// SetMacAddressNil sets the value for MacAddress to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetMacAddressNil() {
	o.MacAddress.Set(nil)
}

// UnsetMacAddress ensures that no value is present for MacAddress, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetMacAddress() {
	o.MacAddress.Unset()
}

// GetRandomizedMacAddress returns the RandomizedMacAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetRandomizedMacAddress() string {
	if o == nil || IsNil(o.RandomizedMacAddress.Get()) {
		var ret string
		return ret
	}
	return *o.RandomizedMacAddress.Get()
}

// GetRandomizedMacAddressOk returns a tuple with the RandomizedMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetRandomizedMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RandomizedMacAddress.Get(), o.RandomizedMacAddress.IsSet()
}

// HasRandomizedMacAddress returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasRandomizedMacAddress() bool {
	if o != nil && o.RandomizedMacAddress.IsSet() {
		return true
	}

	return false
}

// SetRandomizedMacAddress gets a reference to the given NullableString and assigns it to the RandomizedMacAddress field.
func (o *GetDevices200ResponseDataInner) SetRandomizedMacAddress(v string) {
	o.RandomizedMacAddress.Set(&v)
}
// SetRandomizedMacAddressNil sets the value for RandomizedMacAddress to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetRandomizedMacAddressNil() {
	o.RandomizedMacAddress.Set(nil)
}

// UnsetRandomizedMacAddress ensures that no value is present for RandomizedMacAddress, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetRandomizedMacAddress() {
	o.RandomizedMacAddress.Unset()
}

// GetStorageSpaceFreeGb returns the StorageSpaceFreeGb field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetStorageSpaceFreeGb() float32 {
	if o == nil || IsNil(o.StorageSpaceFreeGb.Get()) {
		var ret float32
		return ret
	}
	return *o.StorageSpaceFreeGb.Get()
}

// GetStorageSpaceFreeGbOk returns a tuple with the StorageSpaceFreeGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetStorageSpaceFreeGbOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageSpaceFreeGb.Get(), o.StorageSpaceFreeGb.IsSet()
}

// HasStorageSpaceFreeGb returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasStorageSpaceFreeGb() bool {
	if o != nil && o.StorageSpaceFreeGb.IsSet() {
		return true
	}

	return false
}

// SetStorageSpaceFreeGb gets a reference to the given NullableFloat32 and assigns it to the StorageSpaceFreeGb field.
func (o *GetDevices200ResponseDataInner) SetStorageSpaceFreeGb(v float32) {
	o.StorageSpaceFreeGb.Set(&v)
}
// SetStorageSpaceFreeGbNil sets the value for StorageSpaceFreeGb to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetStorageSpaceFreeGbNil() {
	o.StorageSpaceFreeGb.Set(nil)
}

// UnsetStorageSpaceFreeGb ensures that no value is present for StorageSpaceFreeGb, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetStorageSpaceFreeGb() {
	o.StorageSpaceFreeGb.Unset()
}

// GetStorageSpaceTotalGb returns the StorageSpaceTotalGb field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetStorageSpaceTotalGb() float32 {
	if o == nil || IsNil(o.StorageSpaceTotalGb.Get()) {
		var ret float32
		return ret
	}
	return *o.StorageSpaceTotalGb.Get()
}

// GetStorageSpaceTotalGbOk returns a tuple with the StorageSpaceTotalGb field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetStorageSpaceTotalGbOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageSpaceTotalGb.Get(), o.StorageSpaceTotalGb.IsSet()
}

// HasStorageSpaceTotalGb returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasStorageSpaceTotalGb() bool {
	if o != nil && o.StorageSpaceTotalGb.IsSet() {
		return true
	}

	return false
}

// SetStorageSpaceTotalGb gets a reference to the given NullableFloat32 and assigns it to the StorageSpaceTotalGb field.
func (o *GetDevices200ResponseDataInner) SetStorageSpaceTotalGb(v float32) {
	o.StorageSpaceTotalGb.Set(&v)
}
// SetStorageSpaceTotalGbNil sets the value for StorageSpaceTotalGb to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetStorageSpaceTotalGbNil() {
	o.StorageSpaceTotalGb.Set(nil)
}

// UnsetStorageSpaceTotalGb ensures that no value is present for StorageSpaceTotalGb, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetStorageSpaceTotalGb() {
	o.StorageSpaceTotalGb.Unset()
}

// GetBatteryHealth returns the BatteryHealth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetBatteryHealth() string {
	if o == nil || IsNil(o.BatteryHealth.Get()) {
		var ret string
		return ret
	}
	return *o.BatteryHealth.Get()
}

// GetBatteryHealthOk returns a tuple with the BatteryHealth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetBatteryHealthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BatteryHealth.Get(), o.BatteryHealth.IsSet()
}

// HasBatteryHealth returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasBatteryHealth() bool {
	if o != nil && o.BatteryHealth.IsSet() {
		return true
	}

	return false
}

// SetBatteryHealth gets a reference to the given NullableString and assigns it to the BatteryHealth field.
func (o *GetDevices200ResponseDataInner) SetBatteryHealth(v string) {
	o.BatteryHealth.Set(&v)
}
// SetBatteryHealthNil sets the value for BatteryHealth to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetBatteryHealthNil() {
	o.BatteryHealth.Set(nil)
}

// UnsetBatteryHealth ensures that no value is present for BatteryHealth, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetBatteryHealth() {
	o.BatteryHealth.Unset()
}

// GetBatteryCharging returns the BatteryCharging field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetBatteryCharging() bool {
	if o == nil || IsNil(o.BatteryCharging.Get()) {
		var ret bool
		return ret
	}
	return *o.BatteryCharging.Get()
}

// GetBatteryChargingOk returns a tuple with the BatteryCharging field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetBatteryChargingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.BatteryCharging.Get(), o.BatteryCharging.IsSet()
}

// HasBatteryCharging returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasBatteryCharging() bool {
	if o != nil && o.BatteryCharging.IsSet() {
		return true
	}

	return false
}

// SetBatteryCharging gets a reference to the given NullableBool and assigns it to the BatteryCharging field.
func (o *GetDevices200ResponseDataInner) SetBatteryCharging(v bool) {
	o.BatteryCharging.Set(&v)
}
// SetBatteryChargingNil sets the value for BatteryCharging to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetBatteryChargingNil() {
	o.BatteryCharging.Set(nil)
}

// UnsetBatteryCharging ensures that no value is present for BatteryCharging, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetBatteryCharging() {
	o.BatteryCharging.Unset()
}

// GetBatteryPercentage returns the BatteryPercentage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetBatteryPercentage() int32 {
	if o == nil || IsNil(o.BatteryPercentage.Get()) {
		var ret int32
		return ret
	}
	return *o.BatteryPercentage.Get()
}

// GetBatteryPercentageOk returns a tuple with the BatteryPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetBatteryPercentageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BatteryPercentage.Get(), o.BatteryPercentage.IsSet()
}

// HasBatteryPercentage returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasBatteryPercentage() bool {
	if o != nil && o.BatteryPercentage.IsSet() {
		return true
	}

	return false
}

// SetBatteryPercentage gets a reference to the given NullableInt32 and assigns it to the BatteryPercentage field.
func (o *GetDevices200ResponseDataInner) SetBatteryPercentage(v int32) {
	o.BatteryPercentage.Set(&v)
}
// SetBatteryPercentageNil sets the value for BatteryPercentage to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetBatteryPercentageNil() {
	o.BatteryPercentage.Set(nil)
}

// UnsetBatteryPercentage ensures that no value is present for BatteryPercentage, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetBatteryPercentage() {
	o.BatteryPercentage.Unset()
}

// GetBatteryTemperatureC returns the BatteryTemperatureC field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetBatteryTemperatureC() float32 {
	if o == nil || IsNil(o.BatteryTemperatureC.Get()) {
		var ret float32
		return ret
	}
	return *o.BatteryTemperatureC.Get()
}

// GetBatteryTemperatureCOk returns a tuple with the BatteryTemperatureC field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetBatteryTemperatureCOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BatteryTemperatureC.Get(), o.BatteryTemperatureC.IsSet()
}

// HasBatteryTemperatureC returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasBatteryTemperatureC() bool {
	if o != nil && o.BatteryTemperatureC.IsSet() {
		return true
	}

	return false
}

// SetBatteryTemperatureC gets a reference to the given NullableFloat32 and assigns it to the BatteryTemperatureC field.
func (o *GetDevices200ResponseDataInner) SetBatteryTemperatureC(v float32) {
	o.BatteryTemperatureC.Set(&v)
}
// SetBatteryTemperatureCNil sets the value for BatteryTemperatureC to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetBatteryTemperatureCNil() {
	o.BatteryTemperatureC.Set(nil)
}

// UnsetBatteryTemperatureC ensures that no value is present for BatteryTemperatureC, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetBatteryTemperatureC() {
	o.BatteryTemperatureC.Unset()
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress.Get()) {
		var ret string
		return ret
	}
	return *o.IpAddress.Get()
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpAddress.Get(), o.IpAddress.IsSet()
}

// HasIpAddress returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasIpAddress() bool {
	if o != nil && o.IpAddress.IsSet() {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given NullableString and assigns it to the IpAddress field.
func (o *GetDevices200ResponseDataInner) SetIpAddress(v string) {
	o.IpAddress.Set(&v)
}
// SetIpAddressNil sets the value for IpAddress to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetIpAddressNil() {
	o.IpAddress.Set(nil)
}

// UnsetIpAddress ensures that no value is present for IpAddress, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetIpAddress() {
	o.IpAddress.Unset()
}

// GetSignalStrength returns the SignalStrength field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetSignalStrength() float32 {
	if o == nil || IsNil(o.SignalStrength.Get()) {
		var ret float32
		return ret
	}
	return *o.SignalStrength.Get()
}

// GetSignalStrengthOk returns a tuple with the SignalStrength field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetSignalStrengthOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SignalStrength.Get(), o.SignalStrength.IsSet()
}

// HasSignalStrength returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasSignalStrength() bool {
	if o != nil && o.SignalStrength.IsSet() {
		return true
	}

	return false
}

// SetSignalStrength gets a reference to the given NullableFloat32 and assigns it to the SignalStrength field.
func (o *GetDevices200ResponseDataInner) SetSignalStrength(v float32) {
	o.SignalStrength.Set(&v)
}
// SetSignalStrengthNil sets the value for SignalStrength to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetSignalStrengthNil() {
	o.SignalStrength.Set(nil)
}

// UnsetSignalStrength ensures that no value is present for SignalStrength, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetSignalStrength() {
	o.SignalStrength.Unset()
}

// GetFrequencyMhz returns the FrequencyMhz field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetFrequencyMhz() int32 {
	if o == nil || IsNil(o.FrequencyMhz.Get()) {
		var ret int32
		return ret
	}
	return *o.FrequencyMhz.Get()
}

// GetFrequencyMhzOk returns a tuple with the FrequencyMhz field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetFrequencyMhzOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FrequencyMhz.Get(), o.FrequencyMhz.IsSet()
}

// HasFrequencyMhz returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasFrequencyMhz() bool {
	if o != nil && o.FrequencyMhz.IsSet() {
		return true
	}

	return false
}

// SetFrequencyMhz gets a reference to the given NullableInt32 and assigns it to the FrequencyMhz field.
func (o *GetDevices200ResponseDataInner) SetFrequencyMhz(v int32) {
	o.FrequencyMhz.Set(&v)
}
// SetFrequencyMhzNil sets the value for FrequencyMhz to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetFrequencyMhzNil() {
	o.FrequencyMhz.Set(nil)
}

// UnsetFrequencyMhz ensures that no value is present for FrequencyMhz, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetFrequencyMhz() {
	o.FrequencyMhz.Unset()
}

// GetLinkSpeedMbps returns the LinkSpeedMbps field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetLinkSpeedMbps() int32 {
	if o == nil || IsNil(o.LinkSpeedMbps.Get()) {
		var ret int32
		return ret
	}
	return *o.LinkSpeedMbps.Get()
}

// GetLinkSpeedMbpsOk returns a tuple with the LinkSpeedMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetLinkSpeedMbpsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LinkSpeedMbps.Get(), o.LinkSpeedMbps.IsSet()
}

// HasLinkSpeedMbps returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasLinkSpeedMbps() bool {
	if o != nil && o.LinkSpeedMbps.IsSet() {
		return true
	}

	return false
}

// SetLinkSpeedMbps gets a reference to the given NullableInt32 and assigns it to the LinkSpeedMbps field.
func (o *GetDevices200ResponseDataInner) SetLinkSpeedMbps(v int32) {
	o.LinkSpeedMbps.Set(&v)
}
// SetLinkSpeedMbpsNil sets the value for LinkSpeedMbps to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetLinkSpeedMbpsNil() {
	o.LinkSpeedMbps.Set(nil)
}

// UnsetLinkSpeedMbps ensures that no value is present for LinkSpeedMbps, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetLinkSpeedMbps() {
	o.LinkSpeedMbps.Unset()
}

// GetLastLocationLatitude returns the LastLocationLatitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetLastLocationLatitude() float32 {
	if o == nil || IsNil(o.LastLocationLatitude.Get()) {
		var ret float32
		return ret
	}
	return *o.LastLocationLatitude.Get()
}

// GetLastLocationLatitudeOk returns a tuple with the LastLocationLatitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetLastLocationLatitudeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastLocationLatitude.Get(), o.LastLocationLatitude.IsSet()
}

// HasLastLocationLatitude returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasLastLocationLatitude() bool {
	if o != nil && o.LastLocationLatitude.IsSet() {
		return true
	}

	return false
}

// SetLastLocationLatitude gets a reference to the given NullableFloat32 and assigns it to the LastLocationLatitude field.
func (o *GetDevices200ResponseDataInner) SetLastLocationLatitude(v float32) {
	o.LastLocationLatitude.Set(&v)
}
// SetLastLocationLatitudeNil sets the value for LastLocationLatitude to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetLastLocationLatitudeNil() {
	o.LastLocationLatitude.Set(nil)
}

// UnsetLastLocationLatitude ensures that no value is present for LastLocationLatitude, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetLastLocationLatitude() {
	o.LastLocationLatitude.Unset()
}

// GetLastLocationLongitude returns the LastLocationLongitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetLastLocationLongitude() float32 {
	if o == nil || IsNil(o.LastLocationLongitude.Get()) {
		var ret float32
		return ret
	}
	return *o.LastLocationLongitude.Get()
}

// GetLastLocationLongitudeOk returns a tuple with the LastLocationLongitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetLastLocationLongitudeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastLocationLongitude.Get(), o.LastLocationLongitude.IsSet()
}

// HasLastLocationLongitude returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasLastLocationLongitude() bool {
	if o != nil && o.LastLocationLongitude.IsSet() {
		return true
	}

	return false
}

// SetLastLocationLongitude gets a reference to the given NullableFloat32 and assigns it to the LastLocationLongitude field.
func (o *GetDevices200ResponseDataInner) SetLastLocationLongitude(v float32) {
	o.LastLocationLongitude.Set(&v)
}
// SetLastLocationLongitudeNil sets the value for LastLocationLongitude to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetLastLocationLongitudeNil() {
	o.LastLocationLongitude.Set(nil)
}

// UnsetLastLocationLongitude ensures that no value is present for LastLocationLongitude, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetLastLocationLongitude() {
	o.LastLocationLongitude.Unset()
}

// GetLastLocationAt returns the LastLocationAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDevices200ResponseDataInner) GetLastLocationAt() string {
	if o == nil || IsNil(o.LastLocationAt.Get()) {
		var ret string
		return ret
	}
	return *o.LastLocationAt.Get()
}

// GetLastLocationAtOk returns a tuple with the LastLocationAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDevices200ResponseDataInner) GetLastLocationAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastLocationAt.Get(), o.LastLocationAt.IsSet()
}

// HasLastLocationAt returns a boolean if a field has been set.
func (o *GetDevices200ResponseDataInner) HasLastLocationAt() bool {
	if o != nil && o.LastLocationAt.IsSet() {
		return true
	}

	return false
}

// SetLastLocationAt gets a reference to the given NullableString and assigns it to the LastLocationAt field.
func (o *GetDevices200ResponseDataInner) SetLastLocationAt(v string) {
	o.LastLocationAt.Set(&v)
}
// SetLastLocationAtNil sets the value for LastLocationAt to be an explicit nil
func (o *GetDevices200ResponseDataInner) SetLastLocationAtNil() {
	o.LastLocationAt.Set(nil)
}

// UnsetLastLocationAt ensures that no value is present for LastLocationAt, not even an explicit nil
func (o *GetDevices200ResponseDataInner) UnsetLastLocationAt() {
	o.LastLocationAt.Unset()
}

func (o GetDevices200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDevices200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.SerialNumber) {
		toSerialize["serialNumber"] = o.SerialNumber
	}
	if o.DeviceGroup.IsSet() {
		toSerialize["deviceGroup"] = o.DeviceGroup.Get()
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.LastCommunicatedAt.IsSet() {
		toSerialize["lastCommunicatedAt"] = o.LastCommunicatedAt.Get()
	}
	if o.IsOnline.IsSet() {
		toSerialize["isOnline"] = o.IsOnline.Get()
	}
	if o.ClientVersion.IsSet() {
		toSerialize["clientVersion"] = o.ClientVersion.Get()
	}
	if o.LauncherVersion.IsSet() {
		toSerialize["launcherVersion"] = o.LauncherVersion.Get()
	}
	if o.EnrollmentDate.IsSet() {
		toSerialize["enrollmentDate"] = o.EnrollmentDate.Get()
	}
	if o.SystemVersion.IsSet() {
		toSerialize["systemVersion"] = o.SystemVersion.Get()
	}
	if o.OsVersion.IsSet() {
		toSerialize["osVersion"] = o.OsVersion.Get()
	}
	if o.Ssid.IsSet() {
		toSerialize["ssid"] = o.Ssid.Get()
	}
	if o.MacAddress.IsSet() {
		toSerialize["macAddress"] = o.MacAddress.Get()
	}
	if o.RandomizedMacAddress.IsSet() {
		toSerialize["randomizedMacAddress"] = o.RandomizedMacAddress.Get()
	}
	if o.StorageSpaceFreeGb.IsSet() {
		toSerialize["storageSpaceFreeGb"] = o.StorageSpaceFreeGb.Get()
	}
	if o.StorageSpaceTotalGb.IsSet() {
		toSerialize["storageSpaceTotalGb"] = o.StorageSpaceTotalGb.Get()
	}
	if o.BatteryHealth.IsSet() {
		toSerialize["batteryHealth"] = o.BatteryHealth.Get()
	}
	if o.BatteryCharging.IsSet() {
		toSerialize["batteryCharging"] = o.BatteryCharging.Get()
	}
	if o.BatteryPercentage.IsSet() {
		toSerialize["batteryPercentage"] = o.BatteryPercentage.Get()
	}
	if o.BatteryTemperatureC.IsSet() {
		toSerialize["batteryTemperatureC"] = o.BatteryTemperatureC.Get()
	}
	if o.IpAddress.IsSet() {
		toSerialize["ipAddress"] = o.IpAddress.Get()
	}
	if o.SignalStrength.IsSet() {
		toSerialize["signalStrength"] = o.SignalStrength.Get()
	}
	if o.FrequencyMhz.IsSet() {
		toSerialize["frequencyMhz"] = o.FrequencyMhz.Get()
	}
	if o.LinkSpeedMbps.IsSet() {
		toSerialize["linkSpeedMbps"] = o.LinkSpeedMbps.Get()
	}
	if o.LastLocationLatitude.IsSet() {
		toSerialize["lastLocationLatitude"] = o.LastLocationLatitude.Get()
	}
	if o.LastLocationLongitude.IsSet() {
		toSerialize["lastLocationLongitude"] = o.LastLocationLongitude.Get()
	}
	if o.LastLocationAt.IsSet() {
		toSerialize["lastLocationAt"] = o.LastLocationAt.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetDevices200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	varGetDevices200ResponseDataInner := _GetDevices200ResponseDataInner{}

	err = json.Unmarshal(data, &varGetDevices200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = GetDevices200ResponseDataInner(varGetDevices200ResponseDataInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "title")
		delete(additionalProperties, "serialNumber")
		delete(additionalProperties, "deviceGroup")
		delete(additionalProperties, "group")
		delete(additionalProperties, "model")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "lastCommunicatedAt")
		delete(additionalProperties, "isOnline")
		delete(additionalProperties, "clientVersion")
		delete(additionalProperties, "launcherVersion")
		delete(additionalProperties, "enrollmentDate")
		delete(additionalProperties, "systemVersion")
		delete(additionalProperties, "osVersion")
		delete(additionalProperties, "ssid")
		delete(additionalProperties, "macAddress")
		delete(additionalProperties, "randomizedMacAddress")
		delete(additionalProperties, "storageSpaceFreeGb")
		delete(additionalProperties, "storageSpaceTotalGb")
		delete(additionalProperties, "batteryHealth")
		delete(additionalProperties, "batteryCharging")
		delete(additionalProperties, "batteryPercentage")
		delete(additionalProperties, "batteryTemperatureC")
		delete(additionalProperties, "ipAddress")
		delete(additionalProperties, "signalStrength")
		delete(additionalProperties, "frequencyMhz")
		delete(additionalProperties, "linkSpeedMbps")
		delete(additionalProperties, "lastLocationLatitude")
		delete(additionalProperties, "lastLocationLongitude")
		delete(additionalProperties, "lastLocationAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetDevices200ResponseDataInner struct {
	value *GetDevices200ResponseDataInner
	isSet bool
}

func (v NullableGetDevices200ResponseDataInner) Get() *GetDevices200ResponseDataInner {
	return v.value
}

func (v *NullableGetDevices200ResponseDataInner) Set(val *GetDevices200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDevices200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDevices200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDevices200ResponseDataInner(val *GetDevices200ResponseDataInner) *NullableGetDevices200ResponseDataInner {
	return &NullableGetDevices200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetDevices200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDevices200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


