/*
ArborXR Public API

This API provides a RESTful interface to interact with your organization's data.

API version: v2
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetApps200ResponseDataInnerDeviceModelsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetApps200ResponseDataInnerDeviceModelsInner{}

// GetApps200ResponseDataInnerDeviceModelsInner struct for GetApps200ResponseDataInnerDeviceModelsInner
type GetApps200ResponseDataInnerDeviceModelsInner struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Manufacturer *string `json:"manufacturer,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetApps200ResponseDataInnerDeviceModelsInner GetApps200ResponseDataInnerDeviceModelsInner

// NewGetApps200ResponseDataInnerDeviceModelsInner instantiates a new GetApps200ResponseDataInnerDeviceModelsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApps200ResponseDataInnerDeviceModelsInner() *GetApps200ResponseDataInnerDeviceModelsInner {
	this := GetApps200ResponseDataInnerDeviceModelsInner{}
	return &this
}

// NewGetApps200ResponseDataInnerDeviceModelsInnerWithDefaults instantiates a new GetApps200ResponseDataInnerDeviceModelsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApps200ResponseDataInnerDeviceModelsInnerWithDefaults() *GetApps200ResponseDataInnerDeviceModelsInner {
	this := GetApps200ResponseDataInnerDeviceModelsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetApps200ResponseDataInnerDeviceModelsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApps200ResponseDataInnerDeviceModelsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetApps200ResponseDataInnerDeviceModelsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetApps200ResponseDataInnerDeviceModelsInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetApps200ResponseDataInnerDeviceModelsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApps200ResponseDataInnerDeviceModelsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetApps200ResponseDataInnerDeviceModelsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetApps200ResponseDataInnerDeviceModelsInner) SetName(v string) {
	o.Name = &v
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise.
func (o *GetApps200ResponseDataInnerDeviceModelsInner) GetManufacturer() string {
	if o == nil || IsNil(o.Manufacturer) {
		var ret string
		return ret
	}
	return *o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApps200ResponseDataInnerDeviceModelsInner) GetManufacturerOk() (*string, bool) {
	if o == nil || IsNil(o.Manufacturer) {
		return nil, false
	}
	return o.Manufacturer, true
}

// HasManufacturer returns a boolean if a field has been set.
func (o *GetApps200ResponseDataInnerDeviceModelsInner) HasManufacturer() bool {
	if o != nil && !IsNil(o.Manufacturer) {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given string and assigns it to the Manufacturer field.
func (o *GetApps200ResponseDataInnerDeviceModelsInner) SetManufacturer(v string) {
	o.Manufacturer = &v
}

func (o GetApps200ResponseDataInnerDeviceModelsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetApps200ResponseDataInnerDeviceModelsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Manufacturer) {
		toSerialize["manufacturer"] = o.Manufacturer
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetApps200ResponseDataInnerDeviceModelsInner) UnmarshalJSON(data []byte) (err error) {
	varGetApps200ResponseDataInnerDeviceModelsInner := _GetApps200ResponseDataInnerDeviceModelsInner{}

	err = json.Unmarshal(data, &varGetApps200ResponseDataInnerDeviceModelsInner)

	if err != nil {
		return err
	}

	*o = GetApps200ResponseDataInnerDeviceModelsInner(varGetApps200ResponseDataInnerDeviceModelsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "manufacturer")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetApps200ResponseDataInnerDeviceModelsInner struct {
	value *GetApps200ResponseDataInnerDeviceModelsInner
	isSet bool
}

func (v NullableGetApps200ResponseDataInnerDeviceModelsInner) Get() *GetApps200ResponseDataInnerDeviceModelsInner {
	return v.value
}

func (v *NullableGetApps200ResponseDataInnerDeviceModelsInner) Set(val *GetApps200ResponseDataInnerDeviceModelsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApps200ResponseDataInnerDeviceModelsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApps200ResponseDataInnerDeviceModelsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApps200ResponseDataInnerDeviceModelsInner(val *GetApps200ResponseDataInnerDeviceModelsInner) *NullableGetApps200ResponseDataInnerDeviceModelsInner {
	return &NullableGetApps200ResponseDataInnerDeviceModelsInner{value: val, isSet: true}
}

func (v NullableGetApps200ResponseDataInnerDeviceModelsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetApps200ResponseDataInnerDeviceModelsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


