/*
arborxr-api-v2

This API provides a RESTful interface to interact with your organization's data.

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arbor-api-go

import (
	"encoding/json"
	"fmt"
)

// checks if the AppsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppsResponse{}

// AppsResponse A paginated list of apps.
type AppsResponse struct {
	Data []AppWithDeviceModels `json:"data"`
	Links Links `json:"links"`
	Meta Meta `json:"meta"`
	AdditionalProperties map[string]interface{}
}

type _AppsResponse AppsResponse

// NewAppsResponse instantiates a new AppsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppsResponse(data []AppWithDeviceModels, links Links, meta Meta) *AppsResponse {
	this := AppsResponse{}
	this.Data = data
	this.Links = links
	this.Meta = meta
	return &this
}

// NewAppsResponseWithDefaults instantiates a new AppsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppsResponseWithDefaults() *AppsResponse {
	this := AppsResponse{}
	return &this
}

// GetData returns the Data field value
func (o *AppsResponse) GetData() []AppWithDeviceModels {
	if o == nil {
		var ret []AppWithDeviceModels
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AppsResponse) GetDataOk() ([]AppWithDeviceModels, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *AppsResponse) SetData(v []AppWithDeviceModels) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *AppsResponse) GetLinks() Links {
	if o == nil {
		var ret Links
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *AppsResponse) GetLinksOk() (*Links, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *AppsResponse) SetLinks(v Links) {
	o.Links = v
}

// GetMeta returns the Meta field value
func (o *AppsResponse) GetMeta() Meta {
	if o == nil {
		var ret Meta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *AppsResponse) GetMetaOk() (*Meta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *AppsResponse) SetMeta(v Meta) {
	o.Meta = v
}

func (o AppsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	toSerialize["meta"] = o.Meta

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AppsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppsResponse := _AppsResponse{}

	err = json.Unmarshal(data, &varAppsResponse)

	if err != nil {
		return err
	}

	*o = AppsResponse(varAppsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "links")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppsResponse struct {
	value *AppsResponse
	isSet bool
}

func (v NullableAppsResponse) Get() *AppsResponse {
	return v.value
}

func (v *NullableAppsResponse) Set(val *AppsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAppsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAppsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppsResponse(val *AppsResponse) *NullableAppsResponse {
	return &NullableAppsResponse{value: val, isSet: true}
}

func (v NullableAppsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


