/*
arborxr-api-v2

This API provides a RESTful interface to interact with your organization's data.

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Device type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Device{}

// Device Represents a device that is managed by your organization.
type Device struct {
	Id string `json:"id"`
	Title string `json:"title"`
	SerialNumber string `json:"serialNumber"`
	DeviceGroup NullableString `json:"deviceGroup,omitempty"`
	Model string `json:"model"`
	Tags []string `json:"tags"`
	LastCommunicatedAt time.Time `json:"lastCommunicatedAt"`
}

type _Device Device

// NewDevice instantiates a new Device object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDevice(id string, title string, serialNumber string, model string, tags []string, lastCommunicatedAt time.Time) *Device {
	this := Device{}
	this.Id = id
	this.Title = title
	this.SerialNumber = serialNumber
	this.Model = model
	this.Tags = tags
	this.LastCommunicatedAt = lastCommunicatedAt
	return &this
}

// NewDeviceWithDefaults instantiates a new Device object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceWithDefaults() *Device {
	this := Device{}
	return &this
}

// GetId returns the Id field value
func (o *Device) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Device) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Device) SetId(v string) {
	o.Id = v
}

// GetTitle returns the Title field value
func (o *Device) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *Device) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *Device) SetTitle(v string) {
	o.Title = v
}

// GetSerialNumber returns the SerialNumber field value
func (o *Device) GetSerialNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value
// and a boolean to check if the value has been set.
func (o *Device) GetSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SerialNumber, true
}

// SetSerialNumber sets field value
func (o *Device) SetSerialNumber(v string) {
	o.SerialNumber = v
}

// GetDeviceGroup returns the DeviceGroup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Device) GetDeviceGroup() string {
	if o == nil || IsNil(o.DeviceGroup.Get()) {
		var ret string
		return ret
	}
	return *o.DeviceGroup.Get()
}

// GetDeviceGroupOk returns a tuple with the DeviceGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Device) GetDeviceGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceGroup.Get(), o.DeviceGroup.IsSet()
}

// HasDeviceGroup returns a boolean if a field has been set.
func (o *Device) HasDeviceGroup() bool {
	if o != nil && o.DeviceGroup.IsSet() {
		return true
	}

	return false
}

// SetDeviceGroup gets a reference to the given NullableString and assigns it to the DeviceGroup field.
func (o *Device) SetDeviceGroup(v string) {
	o.DeviceGroup.Set(&v)
}
// SetDeviceGroupNil sets the value for DeviceGroup to be an explicit nil
func (o *Device) SetDeviceGroupNil() {
	o.DeviceGroup.Set(nil)
}

// UnsetDeviceGroup ensures that no value is present for DeviceGroup, not even an explicit nil
func (o *Device) UnsetDeviceGroup() {
	o.DeviceGroup.Unset()
}

// GetModel returns the Model field value
func (o *Device) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *Device) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *Device) SetModel(v string) {
	o.Model = v
}

// GetTags returns the Tags field value
func (o *Device) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *Device) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *Device) SetTags(v []string) {
	o.Tags = v
}

// GetLastCommunicatedAt returns the LastCommunicatedAt field value
func (o *Device) GetLastCommunicatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastCommunicatedAt
}

// GetLastCommunicatedAtOk returns a tuple with the LastCommunicatedAt field value
// and a boolean to check if the value has been set.
func (o *Device) GetLastCommunicatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastCommunicatedAt, true
}

// SetLastCommunicatedAt sets field value
func (o *Device) SetLastCommunicatedAt(v time.Time) {
	o.LastCommunicatedAt = v
}

func (o Device) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Device) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["title"] = o.Title
	toSerialize["serialNumber"] = o.SerialNumber
	if o.DeviceGroup.IsSet() {
		toSerialize["deviceGroup"] = o.DeviceGroup.Get()
	}
	toSerialize["model"] = o.Model
	toSerialize["tags"] = o.Tags
	toSerialize["lastCommunicatedAt"] = o.LastCommunicatedAt
	return toSerialize, nil
}

func (o *Device) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"title",
		"serialNumber",
		"model",
		"tags",
		"lastCommunicatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDevice := _Device{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDevice)

	if err != nil {
		return err
	}

	*o = Device(varDevice)

	return err
}

type NullableDevice struct {
	value *Device
	isSet bool
}

func (v NullableDevice) Get() *Device {
	return v.value
}

func (v *NullableDevice) Set(val *Device) {
	v.value = val
	v.isSet = true
}

func (v NullableDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDevice(val *Device) *NullableDevice {
	return &NullableDevice{value: val, isSet: true}
}

func (v NullableDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


