/*
arborxr-api-v2

This API provides a RESTful interface to interact with your organization's data.

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateDeviceValidationErrorBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDeviceValidationErrorBody{}

// UpdateDeviceValidationErrorBody struct for UpdateDeviceValidationErrorBody
type UpdateDeviceValidationErrorBody struct {
	Message string `json:"message"`
	Errors UpdateDeviceValidationErrorBodyErrors `json:"errors"`
	AdditionalProperties map[string]interface{}
}

type _UpdateDeviceValidationErrorBody UpdateDeviceValidationErrorBody

// NewUpdateDeviceValidationErrorBody instantiates a new UpdateDeviceValidationErrorBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDeviceValidationErrorBody(message string, errors UpdateDeviceValidationErrorBodyErrors) *UpdateDeviceValidationErrorBody {
	this := UpdateDeviceValidationErrorBody{}
	this.Message = message
	this.Errors = errors
	return &this
}

// NewUpdateDeviceValidationErrorBodyWithDefaults instantiates a new UpdateDeviceValidationErrorBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDeviceValidationErrorBodyWithDefaults() *UpdateDeviceValidationErrorBody {
	this := UpdateDeviceValidationErrorBody{}
	return &this
}

// GetMessage returns the Message field value
func (o *UpdateDeviceValidationErrorBody) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *UpdateDeviceValidationErrorBody) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *UpdateDeviceValidationErrorBody) SetMessage(v string) {
	o.Message = v
}

// GetErrors returns the Errors field value
func (o *UpdateDeviceValidationErrorBody) GetErrors() UpdateDeviceValidationErrorBodyErrors {
	if o == nil {
		var ret UpdateDeviceValidationErrorBodyErrors
		return ret
	}

	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value
// and a boolean to check if the value has been set.
func (o *UpdateDeviceValidationErrorBody) GetErrorsOk() (*UpdateDeviceValidationErrorBodyErrors, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Errors, true
}

// SetErrors sets field value
func (o *UpdateDeviceValidationErrorBody) SetErrors(v UpdateDeviceValidationErrorBodyErrors) {
	o.Errors = v
}

func (o UpdateDeviceValidationErrorBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDeviceValidationErrorBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["errors"] = o.Errors

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateDeviceValidationErrorBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"errors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDeviceValidationErrorBody := _UpdateDeviceValidationErrorBody{}

	err = json.Unmarshal(data, &varUpdateDeviceValidationErrorBody)

	if err != nil {
		return err
	}

	*o = UpdateDeviceValidationErrorBody(varUpdateDeviceValidationErrorBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		delete(additionalProperties, "errors")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateDeviceValidationErrorBody struct {
	value *UpdateDeviceValidationErrorBody
	isSet bool
}

func (v NullableUpdateDeviceValidationErrorBody) Get() *UpdateDeviceValidationErrorBody {
	return v.value
}

func (v *NullableUpdateDeviceValidationErrorBody) Set(val *UpdateDeviceValidationErrorBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDeviceValidationErrorBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDeviceValidationErrorBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDeviceValidationErrorBody(val *UpdateDeviceValidationErrorBody) *NullableUpdateDeviceValidationErrorBody {
	return &NullableUpdateDeviceValidationErrorBody{value: val, isSet: true}
}

func (v NullableUpdateDeviceValidationErrorBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDeviceValidationErrorBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


