/*
ArborXR Public API

This API provides a RESTful interface to interact with your organization's data.

API version: v2
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetOrganizationRoles200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationRoles200Response{}

// GetOrganizationRoles200Response Get a paginated list of organization-type roles
type GetOrganizationRoles200Response struct {
	Data []GetUsers200ResponseDataInnerOrganizationRole `json:"data,omitempty"`
	Links *GetOrganizationRoles200ResponseLinks `json:"links,omitempty"`
	Meta *GetOrganizationRoles200ResponseMeta `json:"meta,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetOrganizationRoles200Response GetOrganizationRoles200Response

// NewGetOrganizationRoles200Response instantiates a new GetOrganizationRoles200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationRoles200Response() *GetOrganizationRoles200Response {
	this := GetOrganizationRoles200Response{}
	return &this
}

// NewGetOrganizationRoles200ResponseWithDefaults instantiates a new GetOrganizationRoles200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationRoles200ResponseWithDefaults() *GetOrganizationRoles200Response {
	this := GetOrganizationRoles200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetOrganizationRoles200Response) GetData() []GetUsers200ResponseDataInnerOrganizationRole {
	if o == nil || IsNil(o.Data) {
		var ret []GetUsers200ResponseDataInnerOrganizationRole
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationRoles200Response) GetDataOk() ([]GetUsers200ResponseDataInnerOrganizationRole, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetOrganizationRoles200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetUsers200ResponseDataInnerOrganizationRole and assigns it to the Data field.
func (o *GetOrganizationRoles200Response) SetData(v []GetUsers200ResponseDataInnerOrganizationRole) {
	o.Data = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GetOrganizationRoles200Response) GetLinks() GetOrganizationRoles200ResponseLinks {
	if o == nil || IsNil(o.Links) {
		var ret GetOrganizationRoles200ResponseLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationRoles200Response) GetLinksOk() (*GetOrganizationRoles200ResponseLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GetOrganizationRoles200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given GetOrganizationRoles200ResponseLinks and assigns it to the Links field.
func (o *GetOrganizationRoles200Response) SetLinks(v GetOrganizationRoles200ResponseLinks) {
	o.Links = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *GetOrganizationRoles200Response) GetMeta() GetOrganizationRoles200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret GetOrganizationRoles200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationRoles200Response) GetMetaOk() (*GetOrganizationRoles200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *GetOrganizationRoles200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given GetOrganizationRoles200ResponseMeta and assigns it to the Meta field.
func (o *GetOrganizationRoles200Response) SetMeta(v GetOrganizationRoles200ResponseMeta) {
	o.Meta = &v
}

func (o GetOrganizationRoles200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationRoles200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetOrganizationRoles200Response) UnmarshalJSON(data []byte) (err error) {
	varGetOrganizationRoles200Response := _GetOrganizationRoles200Response{}

	err = json.Unmarshal(data, &varGetOrganizationRoles200Response)

	if err != nil {
		return err
	}

	*o = GetOrganizationRoles200Response(varGetOrganizationRoles200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "links")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetOrganizationRoles200Response struct {
	value *GetOrganizationRoles200Response
	isSet bool
}

func (v NullableGetOrganizationRoles200Response) Get() *GetOrganizationRoles200Response {
	return v.value
}

func (v *NullableGetOrganizationRoles200Response) Set(val *GetOrganizationRoles200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationRoles200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationRoles200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationRoles200Response(val *GetOrganizationRoles200Response) *NullableGetOrganizationRoles200Response {
	return &NullableGetOrganizationRoles200Response{value: val, isSet: true}
}

func (v NullableGetOrganizationRoles200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationRoles200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


