/*
ArborXR Public API

This API provides a RESTful interface to interact with your organization's data.

API version: v2
Contact: support@arborxr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arborapi

import (
	"encoding/json"
)

// checks if the GetUsers200ResponseDataInnerGroupRolesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUsers200ResponseDataInnerGroupRolesInner{}

// GetUsers200ResponseDataInnerGroupRolesInner struct for GetUsers200ResponseDataInnerGroupRolesInner
type GetUsers200ResponseDataInnerGroupRolesInner struct {
	Group *GetDeviceGroups200ResponseDataInner `json:"group,omitempty"`
	Role *GetUsers200ResponseDataInnerOrganizationRole `json:"role,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetUsers200ResponseDataInnerGroupRolesInner GetUsers200ResponseDataInnerGroupRolesInner

// NewGetUsers200ResponseDataInnerGroupRolesInner instantiates a new GetUsers200ResponseDataInnerGroupRolesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsers200ResponseDataInnerGroupRolesInner() *GetUsers200ResponseDataInnerGroupRolesInner {
	this := GetUsers200ResponseDataInnerGroupRolesInner{}
	return &this
}

// NewGetUsers200ResponseDataInnerGroupRolesInnerWithDefaults instantiates a new GetUsers200ResponseDataInnerGroupRolesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsers200ResponseDataInnerGroupRolesInnerWithDefaults() *GetUsers200ResponseDataInnerGroupRolesInner {
	this := GetUsers200ResponseDataInnerGroupRolesInner{}
	return &this
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *GetUsers200ResponseDataInnerGroupRolesInner) GetGroup() GetDeviceGroups200ResponseDataInner {
	if o == nil || IsNil(o.Group) {
		var ret GetDeviceGroups200ResponseDataInner
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsers200ResponseDataInnerGroupRolesInner) GetGroupOk() (*GetDeviceGroups200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *GetUsers200ResponseDataInnerGroupRolesInner) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given GetDeviceGroups200ResponseDataInner and assigns it to the Group field.
func (o *GetUsers200ResponseDataInnerGroupRolesInner) SetGroup(v GetDeviceGroups200ResponseDataInner) {
	o.Group = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *GetUsers200ResponseDataInnerGroupRolesInner) GetRole() GetUsers200ResponseDataInnerOrganizationRole {
	if o == nil || IsNil(o.Role) {
		var ret GetUsers200ResponseDataInnerOrganizationRole
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsers200ResponseDataInnerGroupRolesInner) GetRoleOk() (*GetUsers200ResponseDataInnerOrganizationRole, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *GetUsers200ResponseDataInnerGroupRolesInner) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given GetUsers200ResponseDataInnerOrganizationRole and assigns it to the Role field.
func (o *GetUsers200ResponseDataInnerGroupRolesInner) SetRole(v GetUsers200ResponseDataInnerOrganizationRole) {
	o.Role = &v
}

func (o GetUsers200ResponseDataInnerGroupRolesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUsers200ResponseDataInnerGroupRolesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetUsers200ResponseDataInnerGroupRolesInner) UnmarshalJSON(data []byte) (err error) {
	varGetUsers200ResponseDataInnerGroupRolesInner := _GetUsers200ResponseDataInnerGroupRolesInner{}

	err = json.Unmarshal(data, &varGetUsers200ResponseDataInnerGroupRolesInner)

	if err != nil {
		return err
	}

	*o = GetUsers200ResponseDataInnerGroupRolesInner(varGetUsers200ResponseDataInnerGroupRolesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "group")
		delete(additionalProperties, "role")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetUsers200ResponseDataInnerGroupRolesInner struct {
	value *GetUsers200ResponseDataInnerGroupRolesInner
	isSet bool
}

func (v NullableGetUsers200ResponseDataInnerGroupRolesInner) Get() *GetUsers200ResponseDataInnerGroupRolesInner {
	return v.value
}

func (v *NullableGetUsers200ResponseDataInnerGroupRolesInner) Set(val *GetUsers200ResponseDataInnerGroupRolesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsers200ResponseDataInnerGroupRolesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsers200ResponseDataInnerGroupRolesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsers200ResponseDataInnerGroupRolesInner(val *GetUsers200ResponseDataInnerGroupRolesInner) *NullableGetUsers200ResponseDataInnerGroupRolesInner {
	return &NullableGetUsers200ResponseDataInnerGroupRolesInner{value: val, isSet: true}
}

func (v NullableGetUsers200ResponseDataInnerGroupRolesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsers200ResponseDataInnerGroupRolesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


